### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by LordVlad-Neutral** [ddycai/habitica-tracker#4]
Hey there your program seems interesting, but I can't seem to understand how to run it. Is there a requirement list I missed or something ?

**Comment by oswinrodrigues** [comment]
It's a web app. You click on the [URL](https://ddycai.github.io/habitica-tracker/) in the _About_ section, input the credentials requested, and then voila!

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/6795508/161578939-4b4a0465-f1de-42b0-8c99-20340278c2dc.png)

</details>

Though I do agree that it was not immediately obvious or clear to me at first either. This info. is typically included in the `README`, which isn't done here.
